import Container from "react-bootstrap/Container";
import Nav from "react-bootstrap/Nav";
import Navbar from "react-bootstrap/Navbar";
import Offcanvas from "react-bootstrap/Offcanvas";
import "bootstrap/dist/css/bootstrap.min.css"; // 引入 Bootstrap CSS
import style from "./layout.module.css";
import Head from "next/head";
import Link from "next/link";
const navTitle = "CHEN I";
const projectArray = [
  { link: "/project-GoGame", name: "圍棋網站" },
  { link: "/project-Tourism", name: "日本旅遊網站" },
  { link: "/project-GPA", name: "成績計算網站" },
  { link: "/project-SnakeGame", name: "貪食蛇" },
  { link: "/project-Bricks", name: "彈跳球" },
  { link: "/project-MongoDB", name: "MongoDB" },
  { link: "/project-Yoichi", name: "夜市APP" },
];

export default function Layout({ children }) {
  return (
    <div>
      <Head>
        <meta charSet="utf-8" />
        <title>Portfolio</title>
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <meta name="author" content="Oni" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../public/favicon.ico" />
      </Head>

      <Navbar expand={false} fixed="top" className="bg-body-tertiary mb-3">
        <Container fluid>
          <Navbar.Brand
            href="#"
            style={{
              marginLeft: "auto",
              marginRight: "auto",
            }}
          >
            {navTitle}
          </Navbar.Brand>
          <Navbar.Toggle aria-controls={`offcanvasNavbar-expand-${false}`} />
          <Navbar.Offcanvas
            id={`offcanvasNavbar-expand-${false}`}
            aria-labelledby={`offcanvasNavbarLabel-expand-${false}`}
            placement="end"
          >
            <Offcanvas.Header closeButton>
              <Offcanvas.Title id={`offcanvasNavbarLabel-expand-${false}`}>
                <Nav.Link href="/">OverView</Nav.Link>
              </Offcanvas.Title>
            </Offcanvas.Header>
            <Offcanvas.Body>
              <Nav className="justify-content-end flex-grow-1 pe-3">
                <Nav.Link className={style.NavLinkHover} href="/">
                  首頁
                </Nav.Link>
                {projectArray.map((object, index) => (
                  <Nav.Link
                    className={style.NavLinkHover}
                    key={object.name + index}
                    href={object.link}
                  >
                    {object.name}
                  </Nav.Link>
                ))}

                {/* <NavDropdown
                    title="Dropdown"
                    id={`offcanvasNavbarDropdown-expand-${false}`}
                  >
                    <NavDropdown.Item href="#action3">Action</NavDropdown.Item>
                    <NavDropdown.Item href="#action4">
                      Another action
                    </NavDropdown.Item>
                    <NavDropdown.Divider />
                    <NavDropdown.Item href="#action5">
                      Something else here
                    </NavDropdown.Item>
                  </NavDropdown> */}
              </Nav>
              {/* <Form className="d-flex">
                  <Form.Control
                    type="search"
                    placeholder="Search"
                    className="me-2"
                    aria-label="Search"
                  />
                  <Button variant="outline-success">Search</Button>
                </Form> */}
            </Offcanvas.Body>
          </Navbar.Offcanvas>
        </Container>
      </Navbar>
      <section style={{ marginTop: "10vh" }}>{children}</section>
      <footer>
        <div>
          Power by NextJS{" "}
          <img
            style={{ height: "2rem", width: "2rem" }}
            src="/project3/images/ICONS/icons8-nextjs.svg"
            alt="nextjs"
          />
          icons by <a href="https://icons8.com">Icons8</a>
        </div>
      </footer>
    </div>
  );
}
