import Container from "react-bootstrap/Container";
import Nav from "react-bootstrap/Nav";
import Navbar from "react-bootstrap/Navbar";
import Offcanvas from "react-bootstrap/Offcanvas";
import NavDropdown from "react-bootstrap/NavDropdown";
import "bootstrap/dist/css/bootstrap.min.css"; // 引入 Bootstrap CSS
import style from "./layout.module.css";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { useRouter } from "next/router";
import styleB from "../styles/bubble.module.css";

const navTitle = "CHEN I";
const UdemyProjectArray = [
  { link: "/Udemy/project-GoGame", name: "圍棋網站" },
  { link: "/Udemy/project-Tourism", name: "日本旅遊網站" },
  { link: "/Udemy/project-GPA", name: "成績計算網站" },
  { link: "/Udemy/project-SnakeGame", name: "貪食蛇" },
  { link: "/Udemy/project-Bricks", name: "彈跳球" },
  { link: "/Udemy/project-MongoDB", name: "MongoDB" },
];
const ISpanProjectArray = [
  { link: "/ISpan/project-FlipCard", name: "翻卡牌遊戲" },
  { link: "/ISpan/project-OShop", name: "OShop網路商店" },
];
const IndividualProjectArray = [
  { link: "/Oni/project-MyAutoMechine", name: "樹梅派~自動玩遊戲" },
  { link: "/Oni/project-Yoichi", name: "夜市APP" },
];
export default function Layout({ children, bubblestatus }) {
  console.log("bubblestatus=", bubblestatus);
  const router = useRouter();

  const navigateToSamePage = (url) => {
    if (router.asPath !== url) {
      router.push(url);
    }
  };
  return (
    <div style={{ position: "relative" }}>
      <div
        className={`${styleB["bubble-background-wrap"]} bubbleCluster  bubbleShow`}
      >
        <div className={`${styleB.bubble} ${styleB.x1}`}></div>
        <div className={`${styleB.bubble} ${styleB.x2}`}></div>
        <div className={`${styleB.bubble} ${styleB.x3}`}></div>
        <div className={`${styleB.bubble} ${styleB.x4}`}></div>
        <div className={`${styleB.bubble} ${styleB.x5}`}></div>
        <div className={`${styleB.bubble} ${styleB.x6}`}></div>
        <div className={`${styleB.bubble} ${styleB.x7}`}></div>
        <div className={`${styleB.bubble} ${styleB.x8}`}></div>
        <div className={`${styleB.bubble} ${styleB.x9}`}></div>
        <div className={`${styleB.bubble} ${styleB.x10}`}></div>
      </div>
      <Head>
        <meta charSet="utf-8" />
        <title>Portfolio</title>
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <meta name="author" content="Oni" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar
        expand={false}
        className="navbar-expand-lg bg-body-tertiary mb-3"
        sticky="top"
      >
        <Container fluid>
          <Navbar.Brand
            href="#"
            style={{
              marginLeft: "auto",
              marginRight: "auto",
              textAlign: "center",
              transform: "translate(50%,0)",
            }}
          >
            {navTitle}
          </Navbar.Brand>
          <Navbar.Toggle aria-controls={`offcanvasNavbar-expand-${false}`} />
          <Navbar.Offcanvas
            id={`offcanvasNavbar-expand-${false}`}
            aria-labelledby={`offcanvasNavbarLabel-expand-${false}`}
            placement="end"
            style={{ width: "50%" }}
          >
            <Offcanvas.Header closeButton>
              <Offcanvas.Title id={`offcanvasNavbarLabel-expand-${false}`}>
                OverView
              </Offcanvas.Title>
            </Offcanvas.Header>
            <Offcanvas.Body>
              <Nav className="justify-content-end flex-grow-1 pe-3">
                <Nav.Link as={Link} href="/" className={style.NavLinkHover}>
                  首頁
                </Nav.Link>

                <NavDropdown
                  className={style.NavLinkHover}
                  title="獨立開發專案"
                  id={`offcanvasNavbarDropdown-Individual-expand-${false}`}
                >
                  {IndividualProjectArray.map((object, index) => (
                    <NavDropdown.Item
                      className={style.NavLinkHover}
                      key={object.name + index}
                      // as={Link}
                      // href={object.link}
                      onClick={() => {
                        navigateToSamePage(object.link);
                      }}
                    >
                      {object.name}
                    </NavDropdown.Item>
                  ))}
                </NavDropdown>
                <NavDropdown
                  className={style.NavLinkHover}
                  title="UdemyProjects"
                  id={`offcanvasNavbarDropdown-Udemy-expand-${false}`}
                >
                  {UdemyProjectArray.map((object, index) => (
                    <NavDropdown.Item
                      className={style.NavLinkHover}
                      key={object.name + index}
                      // as={Link}
                      // href={object.link}
                      onClick={() => {
                        navigateToSamePage(object.link);
                      }}
                    >
                      {object.name}
                    </NavDropdown.Item>
                  ))}
                </NavDropdown>
                <NavDropdown
                  className={style.NavLinkHover}
                  title="資展國際Projects"
                  id={`offcanvasNavbarDropdown-international-expand-${false}`}
                >
                  {ISpanProjectArray.map((object, index) => (
                    <NavDropdown.Item
                      className={style.NavLinkHover}
                      key={object.name + index}
                      // as={Link}
                      // href={object.link}
                      onClick={() => {
                        navigateToSamePage(object.link);
                      }}
                    >
                      {object.name}
                    </NavDropdown.Item>
                  ))}
                </NavDropdown>
                <Nav.Link
                  className={style.NavLinkHover}
                  // as={Link}
                  // href="/OniNote"
                  onClick={() => {
                    navigateToSamePage("/OniNote");
                  }}
                >
                  筆記
                </Nav.Link>
              </Nav>
              {/* <Form className="d-flex">
                  <Form.Control
                    type="search"
                    placeholder="Search"
                    className="me-2"
                    aria-label="Search"
                  />
                  <Button variant="outline-success">Search</Button>
                </Form> */}
            </Offcanvas.Body>
          </Navbar.Offcanvas>
        </Container>
      </Navbar>

      <section>{children}</section>
      <footer>
        <div style={{ margin: "2rem 0" }}>
          Power by NextJS{" "}
          <Image
            width={48}
            height={48}
            style={{ height: "2rem", width: "2rem" }}
            src="/project3/images/ICONS/icons8-nextjs.svg"
            alt="nextjs"
          />
          icons by <a href="https://icons8.com">Icons8</a>
        </div>
      </footer>
    </div>
  );
}
